#!/bin/bash

read -p "Remove this project entirely? (incl. volumes) (y/n)? " CONT
if [ "$CONT" = "y" ]; then
  ddev delete -Oy
  docker volume rm scroll-v10-data scroll-v11-data
else
  echo "Canceled.";
fi
